init deploy_test run to create buckets

diff --git a/.github/workflows/deploy_test.yml b/.github/workflows/deploy_test.yml
--- a/.github/workflows/deploy_test.yml
+++ b/.github/workflows/deploy_test.yml
@@ -2,10 +2,10 @@ name: Deploy Test
 
 on:
   workflow_dispatch:
-    inputs:
-      releaseTag:
-        description: 'Tag of version to be promoted to test'
-        required: true
+    #inputs:
+     # releaseTag:
+      #  description: 'Tag of version to be promoted to test'
+       # required: true
 
 env:
   TF_VERSION: 0.14.7
@@ -44,7 +44,7 @@ jobs:
           s3_bucket: '${{ env.S3_BUCKET_ARTIFACTS }}'
           dir_name: ${{ github.sha }}
         run: |
-          aws s3 sync s3://$s3_bucket/$dir_name/ dist/bcparks-ar-admin
+       # aws s3 sync s3://$s3_bucket/$dir_name/ dist/bcparks-ar-admin
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
@@ -67,7 +67,7 @@ jobs:
           s3_bucket: '${{ env.S3_BUCKET }}-${{ env.TARGET_ENV }}'
           dir_name: ${{ github.event.inputs.releaseTag }}
         run: |
-          aws s3 sync dist/bcparks-ar-admin s3://$s3_bucket/$dir_name/
+       # aws s3 sync dist/bcparks-ar-admin s3://$s3_bucket/$dir_name/
 
   terragrunt:
     name: Run Terragrunt
@@ -142,12 +142,12 @@ jobs:
           origin_id_assets: ${{ env.ORIGIN_ID_ASSETS }}
         run: terragrunt apply-all --terragrunt-non-interactive
 
-  alert-if-failure:
-    if: ${{ always() && ((needs.s3.result=='failure') || (needs.terragrunt.result=='failure'))}}
-    runs-on: ubuntu-latest
-    needs: [terragrunt, s3]
-    steps:
-      - name: Send alert if building admin-test fails. 
-        id: failure_alert
-        run: |
-          curl -X POST -H 'Content-Type: application/json' --data '{"workflow":"${{github.workflow}}","repo":"${{github.repository}}"}' https://chat.developer.gov.bc.ca/hooks/${{ secrets.ROCKETCHAT_TOKEN }}
+ # alert-if-failure:
+  #  if: ${{ always() && ((needs.s3.result=='failure') || (needs.terragrunt.result=='failure'))}}
+   # runs-on: ubuntu-latest
+    #needs: [terragrunt, s3]
+    #steps:
+     # - name: Send alert if building admin-test fails. 
+      #  id: failure_alert
+       # run: |
+        #  curl -X POST -H 'Content-Type: application/json' --data '{"workflow":"${{github.workflow}}","repo":"${{github.repository}}"}' https://chat.developer.gov.bc.ca/hooks/${{ secrets.ROCKETCHAT_TOKEN }}
